from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.db.database import SessionLocal
from app.db.models import DimProduct, FactExclusiveUseRight


PRODUCT_FIELDS = {
    "normalized_product_name",
    "company_id",
    "company_name_raw",
    "insurance_type",
    "release_year_month",
    "release_year_month_basis",
    "primary_product_type_code",
    "partner_company_name",
    "needs_review",
    "product_status",
    "consolidation_status",
}
EXCLUSIVE_FIELDS = {
    "subject_name",
    "company_id",
    "company_name_normalized",
    "insurance_type",
    "acquired_year_month",
    "exclusivity_months",
    "needs_review",
    "event_status",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Apply a qwen_quality_review_plan CSV generated by the full quality review.")
    parser.add_argument("plan_csv")
    parser.add_argument("--apply", action="store_true")
    return parser.parse_args()


def _after(row: dict[str, str]) -> dict[str, Any]:
    value = row.get("after") or "{}"
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return {}


def main() -> int:
    args = parse_args()
    rows = list(csv.DictReader(Path(args.plan_csv).open("r", encoding="utf-8-sig")))
    updated = skipped = 0
    with SessionLocal() as db:
        for row in rows:
            target_type = row.get("target_type")
            target_id = int(row.get("target_id") or 0)
            after = _after(row)
            if target_type == "product":
                item = db.get(DimProduct, target_id)
                fields = PRODUCT_FIELDS
            elif target_type == "exclusive_right":
                item = db.get(FactExclusiveUseRight, target_id)
                fields = EXCLUSIVE_FIELDS
            else:
                item = None
                fields = set()
            if not item or not after:
                skipped += 1
                continue
            if args.apply:
                for field in fields:
                    if field in after:
                        setattr(item, field, after[field])
                db.flush()
            updated += 1
        if args.apply:
            db.commit()
    print(json.dumps({"status": "completed", "apply": bool(args.apply), "updated": updated, "skipped": skipped}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
